### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by ghost** [gmardok/TelegramFuhrer#1]
Hello, A lot of users are creating bots to manage there guilds as they use telegram was wondering can you add this feature so guild(is a channel) and contains a list of users.

Something like this...

https://github.com/dawgeth/CouchBot/blob/master/src/MTD.CouchBot.Domain/Models/DiscordGuildModel.cs

**Comment by gmardok** [comment]
A lot of plans on my list and a little of time for implementation but this can be a nice feature.

**Comment by ghost** [comment]
@gmardok cool thanks keep up the good work!!

**Comment by ghost** [comment]
@gmardok Would it be okay with you if I apply some of your logic to my bot would you like me to provide you any credits?

**Comment by gmardok** [comment]
@di48l069 yes, you can.

**Comment by ghost** [comment]
@gmardok thanks if you need any credits let me know
